services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: talkclass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: talkclass
    # Remova a linha "ports" para evitar conflito na máquina host.
    # Se você PRECISAR acessar pelo DBeaver, use por exemplo:
    #ports: ["5433:5432"]   # (host 5433 -> container 5432)
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d talkclass || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /workspace
    # OBS: No PowerShell use ${PWD}; no CMD use %cd%
    volumes:
      - ${PWD}/backend:/workspace
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5252
      URLS: http://0.0.0.0:5252
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      DOTNET_WATCH_SUPPRESS_EMOJIS: "1"
      # 🔑 Connection string com a CHAVE que a API realmente lê:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=talkclass;Username=postgres;Password=talkclass
      # (opcional) var alternativa que seu Program.cs também aceita:
      # DEFAULTCONNECTION: Host=db;Port=5432;Database=talkclass;Username=postgres;Password=talkclass
      Jwt__Issuer: TalkClass
      Jwt__Audience: TalkClass.Frontend
      Jwt__Key: "kKc4Hn9M2RzQ8sW1tV5yL0pB7fD3jE6aP9xY2uT4mN8qR5sC1vG7hJ0kL3wZ6bD"
      Jwt__ExpiresMinutes: 40
    ports: ["5252:5252"]
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "
        dotnet restore src/TalkClass.API/TalkClass.API.csproj &&
        dotnet watch --project src/TalkClass.API run --no-restore --urls http://0.0.0.0:5252
      "
    restart: unless-stopped

  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      # o app roda no navegador do host → localhost:5252 está correto
      VITE_API_URL: http://localhost:5252
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_INTERVAL: "200"
    ports: ["5174:5174"]
    depends_on: [api]
    volumes:
      - ${PWD}/frontend:/app
      - web-node-mod:/app/node_modules
    command: >
      sh -lc "
        set -euxo pipefail;
        echo 'Node:' $(node -v) 'NPM:' $(npm -v);
        test -f package.json;
        if [ -f package-lock.json ]; then npm ci; else npm i; fi;
        npx vite --host 0.0.0.0 --port 5174
      "
    restart: unless-stopped

volumes:
  pg-data:
  web-node-mod:
